app_profiles/urls.py
from django.urls import path

from app_profiles.views import RegisterView, PersonalAccount, TopUp, BuyProduct, AuthView

urlpatterns = [
    path('register/', RegisterView, name='register'),
    path('personal_account/', PersonalAccount, name='personal_account'),
    path('top_up/', TopUp, name='top_up'),
    path('buy_product/<int:shop_id>/<int:product_id>/', BuyProduct, name='buy_product'),
    path('login/', AuthView, name='login')
]

marketplace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('app_profiles.urls')),
    path('shop/', include('shop.urls'))
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from shop.views import ProductListView, StatisticView

urlpatterns = [
    path('product_list/', ProductListView.as_view(), name='product-list'),
    path('statistic/', StatisticView, name='statistic'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _


# Create your models here.

class Profile(models.Model):
    STATUS_CHOISES = (
        ('be', 'beginner'),
        ('ad', 'advanced'),
        ('ex', 'expert')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=20, verbose_name=_('name'))
    last_name = models.CharField(max_length=20, verbose_name=_('last_name'))
    date_of_birthday = models.DateField(verbose_name=_('date_of_birthday'))
    balance = models.PositiveIntegerField(verbose_name=_('balance'), default=0)
    status = models.CharField(max_length=2, choices=STATUS_CHOISES, default=STATUS_CHOISES[0], verbose_name=_('status'))
    spent_balance = models.PositiveIntegerField(verbose_name=_('spent balance'), default=0)

    class Meta:
        verbose_name = _('Профиль')
        verbose_name_plural = _('Профили')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

shop/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


# Create your models here.
from app_profiles.models import Profile


class Product(models.Model):
    title = models.CharField(max_length=30, verbose_name=_('title'))
    description = models.TextField(max_length=100, verbose_name=_('description'))
    price = models.PositiveIntegerField(verbose_name=_('price'))

    class Meta:
        ordering = ['title']
        verbose_name = _('product')
        verbose_name_plural = _('products')

    def __str__(self):
        return f'{self.title}'


class Shop(models.Model):
    title = models.CharField(max_length=30, verbose_name=_('title'))
    product = models.ManyToManyField(Product)

    class Meta:
        verbose_name = _('shop')
        verbose_name_plural = _('shops')

    def __str__(self):
        return self.title


class Check(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    date_of_sale = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.product} {self.shop} {self.profile} {self.date_of_sale.strftime("%d/%m/%y")}'

app_profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    date_of_birthday = forms.DateField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'date_of_birthday']

class AuthForm(forms.Form):
    username = forms.CharField(max_length=20, label='Логин')
    password = forms.CharField(strip=False, widget=forms.PasswordInput(), label='Пароль')

app_profiles/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
# Create your views here.
from django.urls import reverse
from django.utils.timezone import now

from app_profiles.forms import UserRegisterForm, AuthForm
from app_profiles.models import Profile

from django.db.models import F

from app_profiles.utils import buy_select_product


def RegisterView(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
        cd = form.cleaned_data
        Profile.objects.create(user=user,
                               first_name=cd['first_name'],
                               last_name=cd['last_name'],
                               date_of_birthday=cd['date_of_birthday'])
        user = authenticate(username=cd['username'], password=cd['password1'])
        login(request, user)
        return redirect(reverse('personal_account'))

    form = UserRegisterForm()
    return render(request, 'app_profiles/register_page.html', {'form': form})


@login_required
def PersonalAccount(request):
    form = AuthForm()
    return render(request, 'app_profiles/personal_account.html', {'form': form})


def TopUp(request):
    if request.method == 'POST':
        profile = request.user.profile
        profile.balance += int(request.POST['count'])
        profile.save()
        return redirect(reverse('personal_account'))


al = 'abvababdfb'


def BuyProduct(request, shop_id, product_id):
    try:
        buy_select_product(request, shop_id, product_id)
        return HttpResponse('Товар куплен')
    except Exception as err:
        return HttpResponse(err.args)


def AuthView(request):
    if request.method == 'POST':
        form = AuthForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            if user:
                if user.is_active:
                    login(request, user)
                    return redirect(request.GET.get('next', '/'))
                else:
                    return HttpResponse('Пользователь не активен')
            else:
                return HttpResponse('Такого пользователя не существует')
        else:
            return HttpResponse('Проверьте правильность заполнения формы')
    form = AuthForm()
    return render(request, 'app_profiles/auth_page.html', {'form': form})

shop/views.py
from datetime import datetime

from django.db.models import Count, Max
from django.shortcuts import render
# Create your views here.
from django.utils import timezone
from django.views import generic

from shop.models import Product, Check


class ProductListView(generic.ListView):
    model = Product
    template_name = 'shop/product_list.html'
    context_object_name = 'products'

def StatisticView(request):
    product = Product.objects.filter(check__date_of_sale__gte=datetime(2023, 3, 12, 0, 0, 0)).annotate(count_in_check=Count('check'))
    return render(request, 'shop/statistic.html', {'product': product})

app_profiles/templates/app_profiles/auth_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'app_profiles/css.css' %}">
    <title>Title</title>
</head>
<body>
<div class="container">
    <h3 class="card-title-text-center">Авторизация</h3>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
            <button type="submit">Войти</button>
        </div>
    </form>
</div>
</body>
</html>

app_profiles/templates/app_profiles/personal_account.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'app_profiles/css.css' %}">
</head>
<body style="background-color: antiquewhite">
<div class="personal-acc-container">
    <div style="text-align: center">
        <h1 class="card-title-text-center">Добро пожаловать, {{ user.profile.first_name }}!</h1>
    </div>
    <div class="personal-acc-text">Ваш баланс составляет: {{ user.profile.balance }} рублей</div>
    <div class="personal-acc-text">Ваш статус: {{ user.profile.status }}</div>
    <div class="personal-acc-text">Пополнить баланс:</div>
    <form class="personal-acc-form" action="{% url 'top_up' %}" method="post">
        {% csrf_token %}
        <input type="text" name="count">
        <button type="submit">Пополнить</button>
    </form>


    <div style="margin: 20px">
        <a href="{% url 'product-list' %}">Перейти на страницу магазина</a>
    </div>
</div>
</body>
</html>

app_profiles/templates/app_profiles/register_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Страница регистрации</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Потвердить</button>
</form>
</body>
</html>

shop/templates/shop/product_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'app_profiles/css.css' %}">
    <title>Title</title>
</head>
<body style="background-color: antiquewhite">
<div style="text-align: center">
    <h1 class="card-title-text-center">Страница товаров</h1>
</div>
<div class="personal-acc-container">
    {% for product in products %}
        <div class="personal-acc-text">
            <p>{{ product.title }}</p>
            <p>{{ product.description }}</p>
            <p>Купить за {{ product.price }} руб.</p>
            <p>Купить в {% for shop in product.shop_set.all %}
                <a href="{% url 'buy_product' shop.id product.id %}">{{ shop }}</a>
            {% endfor %}</p>
        </div>

    {% endfor %}
</div>
</body>
</html>

shop/templates/shop/statistic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Страница статистики</h1>
{% for i in product %}
   <p>{{ i.title }} {{ i.count_in_check }} </p>
{% endfor %}
</body>
</html>